#-------------------------------
# Site Settings
title: 박시현  Judy Sihyon Park
logo: # You can add own logo. For example '/images/logo.png'.
author: Judy Sihyon Park
description: personal website

#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
#    - title: 'Blog'
#      url: '/blog/'
#    - title: 'About'
#      url: '/about/'
    - title: 'Research'
      url: '/research/'
    - title: 'Photography'
      url: '/photography/'
    - title: 'Paintings'
      url: '/paintings/'


#-------------------------------
# Portfolio Settings
portfolio-1-all-the-things:
  portfolio__title: All the Things We've Made
  portfolio__gallery:
    - image: /images/photography/all-the-things/1-.jpg
      title: (title)
      description: (caption)
    - image: /images/photography/all-the-things/18-.jpg
      title: (title)
      description: (caption)      
    - image: /images/photography/all-the-things/2-.jpg
      title: (title)
      description: (caption)
 
    - image: /images/photography/all-the-things/4-.jpg
      title: (title)
      description: (caption)
    - image: /images/photography/all-the-things/5-.jpg
      title: (title)
      description: (caption)         
    - image: /images/photography/all-the-things/8-.jpg
      title: (title)
      description: (caption)

    - image: /images/photography/all-the-things/13-.jpg
      title: (title)
      description: (caption)
    - image: /images/photography/all-the-things/15-.jpg
      title: (title)
      description: (caption)           
    - image: /images/photography/all-the-things/7-.jpg
      title: (title)
      description: (caption)



    - image: /images/photography/all-the-things/10-needs-edits.jpg
      title: (title)
      description: (caption)
    - image: /images/photography/all-the-things/11-.jpg
      title: (title)
      description: (caption)
    - image: /images/photography/all-the-things/12-.jpg
      title: (title)
      description: (caption)

#    - image: /images/photography/all-the-things/14-needs-edits.jpg
#      title: (title)
#      description: (caption)

    - image: /images/photography/all-the-things/9-.jpg
      title: (title)
      description: (caption)  
    - image: /images/photography/all-the-things/6-.jpg
      title: (title)
      description: (caption)   
    - image: /images/photography/all-the-things/17-.jpg
      title: (title)
      description: (caption)               



    - image: /images/photography/all-the-things/20-halloween night.jpg
      title: (title)
      description: (caption)
    - image: /images/photography/all-the-things/19-baby shark.jpg
      title: (title)
      description: (caption)  
    - image: /images/photography/all-the-things/16-.jpg
      title: (title)
      description: (caption)       

       
    #- image: /images/photography/all-the-things/9-.jpg
    #  title: (title)
    #  description: (caption)   

# Portfolio Settings
photo-2-who-will-save:
  portfolio__title: Who Will Save Us Now?
  portfolio__gallery:
    - image: /images/photography/who-will-save/1-girls-2024.jpg
      title: Girls (2024)
      description:
    - image: /images/photography/who-will-save/4-montreal.jpg
      title: Montreal (~2024)
      description: 
    - image: /images/photography/who-will-save/6-club cumming-2025.jpg
      title: Club Cumming (2025)
      description:         

    - image: /images/photography/who-will-save/2-smoke break.jpg
      title: Smoke Break I (~2024)
      description:         
    - image: /images/photography/who-will-save/3-needs-edits.jpg
      title: At Thy Shrine (~2024)
      description:         
    - image: /images/photography/who-will-save/8-smoke break II-2025.jpg
      title: Smoke Break II (2025)
      description:  

    - image: /images/photography/who-will-save/7-unstuck in time in woodside, queens.jpg
      title: Unstuck in Time at Woodside Station (2025)
      description:         
    - image: /images/photography/who-will-save/5-penn station superhero.jpg
      title: Untitled (2025)
      description:  

# Portfolio Settings - paintings
paintings-1:
  portfolio__title: Paintings
  portfolio__gallery:

    - image: /images/paintings/dream canyon pink skies-2025-acrylic on canvas-in.jpg
      title: dream canyon pink skies (2025)
      description: acrylic on canvas, 10x20 in.

    - image: /images/paintings/evening on avenue casgrain, 2023, acrylic on canvas, 24x30 in.jpg
      title: Evening on avenue casgrain (2023)
      description: acrylic on canvas, 24×30 in.      

    - image: /images/paintings/Ladylike-2019-acrylic on canvas-12x15in.jpg
      title: Ladylike (2019)
      description: acrylic on canvas, 12×15 in.       


    - image: /images/paintings/primordial contemplations-2023-oil on canvas-in.jpg
      title: Primordial Contemplations (2023)
      description: oil on canvas     
    - image: /images/paintings/Dancer - newer photo.jpg
      title: Dancer (2020)
      description: acrylic on canvas, 30x40 in.     

    - image: /images/paintings/halmoni-2023-acrylic on found wood-in.jpg
      title: Halmoni (2023)
      description: acrylic on found wood         


    - image: /images/paintings/Portrait of a Woman on Prozac-2019- acrylic on canvas 20x16in.jpg
      title: Portrait of a Woman on Prozac (2019)
      description: acrylic on canvas, 20×16 in.
    - image: /images/paintings/Untitled Door-2018-acrylic on found wood-80x30in.jpg
      title: Untitled Door (2018)
      description: acrylic on found wood, 80×30 in.
    - image: /images/paintings/Morning by the Window, 2017, acrylic on canvas, 12x10 in.png
      title: Morning by the Window (2017)
      description: acrylic on canvas, 12×10 in.
    - image: /images/paintings/Campbells-Soup-2019-acrylic on canvas-20x20in.jpg
      title: Ceci Ne Pas Campbells Soup (2019)
      description: acrylic on canvas, 20×20 in.
    - image: /images/paintings/post nut clarity- 2017-acrylic on canvas- 10x10in.jpg
      title: Post Nut Clarity (2017)
      description: acrylic on canvas, 10×10 in.


#-------------------------------
# Subscribe Settings
# mailchimp:
#   mailchimp__title: Get updates and digital art inspiration # Add your Title
#   mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
#   mailchimp__button__text: Subscribe # Add your button text.
#   mailchimp__bg__color: "#f2eef8" # To change the color of the figure, add a hexadecimal color code (HEX). For example - "#f2eef8" (You can generate any color here - https://htmlcolorcodes.com/).


#-------------------------------
# Contact Settings
contact:
  email: judy.se.park@gmail.com # Add your email for contact form
  description: contact form

# NOTE
# Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id